server :
  port : 8000

spring:
  application:
    name: cloud-consumer-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: order8000